## Pandas

In [3]:
import pandas as pd
df = pd.read_csv("C:\\Users\Ibad\Desktop\Cricket.csv")
df.head()
df.tail()
df.describe()

           Overs  Runs Given    Catches
count  50.000000   50.000000  50.000000
mean    3.012000   27.660000   0.720000
std     0.978262   11.690935   0.881557
min     1.000000    8.000000   0.000000
25%     2.125000   19.250000   0.000000
50%     3.000000   23.500000   0.000000
75%     4.000000   37.750000   1.000000
max     4.000000   51.000000   3.000000

In [35]:
df[2:10] #slicing of rows

,Stadium,Team,Toss,Bat,Bowl,Last Matches Performance,Last 3 Matches Performance,Last 6 Matches Performance,Weather,Pitch,Overs,Runs Given,Catches,Win OR Loss,Performance/Wickets
2,OVAL,ZIM,WIN,True,False,BAD,GOOD,GOOD,Overcast,GREEN,3.0,24,0,WIN,Taken
3,BUFFALO PARK,ZIM,WIN,True,False,GOOD,NORMAL,NORMAL,Overcast,DUSTY,4.0,23,0,WIN,Taken
4,NEWLANDS CRICKET GROUND,SL,WIN,False,True,NORMAL,BAD,NORMAL,Windy,DUSTY,3.4,21,2,WIN,Taken
5,OVAL,ENG,LOSS,True,False,GOOD,BAD,GOOD,Windy,DEAD,4.0,45,1,LOSS,Not Taken
6,SUPER SPORT STADIUM,WI,WIN,False,True,NORMAL,GOOD,GOOD,Cool,DEAD,2.0,35,0,WIN,Taken
7,MELBOURNE,AUS,WIN,False,True,BAD,NORMAL,BAD,Cool,GREEN,3.0,24,2,LOSS,Taken
8,LORD'S,AUS,WIN,True,False,BAD,GOOD,BAD,Windy,GREEN,2.0,19,0,LOSS,Taken
9,OVAL,ENG,LOSS,True,False,NORMAL,GOOD,BAD,Sunny,DEAD,4.0,37,0,LOSS,Not Taken

In [37]:
df.columns

Index(['Stadium', 'Team', 'Toss', 'Bat', 'Bowl', 'Last Matches Performance',
       'Last 3 Matches Performance', 'Last 6 Matches Performance', 'Weather',
       'Pitch', 'Overs', 'Runs Given', 'Catches', 'Win OR Loss',
       'Performance/Wickets'],
      dtype='object')

In [42]:
df.Weather #df["Weather"] both for selecting columns

0        Sunny
1        Sunny
2     Overcast
3     Overcast
4        Windy
5        Windy
6         Cool
7         Cool
8        Windy
9        Sunny
10       Windy
11        Cool
12        Cool
13    Overcast
14    Overcast
15       Sunny
16       Windy
17       Windy
18        Cool
19        Cool
20        Cool
21    Overcast
22    Overcast
23    Overcast
24       Sunny
25       Sunny
26    Overcast
27    Overcast
28        Cool
29        Cool
30        Cool
31       Sunny
32       Sunny
33        Cool
34        Cool
35    Overcast
36    Overcast
37       Windy
38       Sunny
39        Cool
40       Windy
41       Sunny
42       Windy
43       Sunny
44       Sunny
45       Sunny
46        Cool
47        Cool
48    Overcast
49    Overcast
Name: Weather, dtype: object

In [54]:
df[["Weather","Pitch"]] #selecting multiple columns

   Weather  Pitch
0     Cool  DUSTY
1     Cool  GREEN
2     Cool  GREEN
3     Cool  DUSTY
4     Cool  DUSTY
5     Cool   DEAD
6     Cool   DEAD
7     Cool  GREEN
8     Cool  GREEN
9     Cool   DEAD
10    Cool   DEAD
11    Cool  DUSTY
12    Cool  DUSTY
13    Cool  GREEN
14    Cool  GREEN
15    Cool   DEAD
16    Cool    DRY
17    Cool  GREEN
18    Cool   DEAD
19    Cool  GREEN
20    Cool   DEAD
21    Cool  DUSTY
22    Cool  GREEN
23    Cool  GREEN
24    Cool  DUSTY
25    Cool  DUSTY
26    Cool   DEAD
27    Cool  GREEN
28    Cool    DRY
29    Cool    DRY
30    Cool  DUSTY
31    Cool   DEAD
32    Cool   DEAD
33    Cool   DEAD
34    Cool  GREEN
35    Cool  DUSTY
36    Cool   DEAD
37    Cool  GREEN
38    Cool  GREEN
39    Cool    DRY
40    Cool  GREEN
41    Cool  GREEN
42    Cool  GREEN
43    Cool   DEAD
44    Cool  GREEN
45    Cool  DUSTY
46    Cool  DUSTY
47    Cool    DRY
48    Cool  DUSTY
49    Cool    DRY

In [58]:
df["Runs Given"].max()

51

In [60]:
df["Runs Given"].min()

8

In [62]:
df[df.Pitch == str.upper("Dusty")] #select data using any condition

,Stadium,Team,Toss,Bat,Bowl,Last Matches Performance,Last 3 Matches Performance,Last 6 Matches Performance,Weather,Pitch,Overs,Runs Given,Catches,Win OR Loss,Performance/Wickets
0,VCA STADIUM,WI,LOSS,True,False,GOOD,GOOD,BAD,Cool,DUSTY,4.0,13,0,LOSS,Taken
3,BUFFALO PARK,ZIM,WIN,True,False,GOOD,NORMAL,NORMAL,Cool,DUSTY,4.0,23,0,WIN,Taken
4,NEWLANDS CRICKET GROUND,SL,WIN,False,True,NORMAL,BAD,NORMAL,Cool,DUSTY,3.4,21,2,WIN,Taken
11,LORD'S,ENG,WIN,False,True,GOOD,GOOD,GOOD,Cool,DUSTY,2.1,21,0,WIN,Not Taken
12,VCA STADIUM,SL,WIN,True,False,BAD,NORMAL,NORMAL,Cool,DUSTY,4.0,35,2,LOSS,Taken
21,EDGBASTON,NZ,WIN,False,True,GOOD,GOOD,NORMAL,Cool,DUSTY,4.0,41,1,WIN,Taken
24,VCA STADIUM,BAN,WIN,True,False,NORMAL,NORMAL,GOOD,Cool,DUSTY,2.0,23,1,LOSS,Taken
25,VCA STADIUM,PAK,WIN,True,False,BAD,BAD,NORMAL,Cool,DUSTY,1.0,12,0,WIN,Not Taken
30,EDGBASTON,AUS,LOSS,False,True,BAD,NORMAL,BAD,Cool,DUSTY,1.0,8,0,LOSS,Not Taken
35,LORD'S,AUS,WIN,False,True,BAD,BAD,GOOD,Cool,DUSTY,3.0,30,0,WIN,Not Taken
45,NEWLANDS CRICKET GROUND,ENG,LOSS,False,True,GOOD,NORMAL,BAD,Cool,DUSTY,3.0,17,0,LOSS,Taken
46,LORD'S,IND,LOSS,False,True,GOOD,BAD,NORMAL,Cool,DUSTY,2.2,21,2,LOSS,Taken
48,LORD'S,BAN,WIN,True,False,BAD,GOOD,GOOD,Cool,DUSTY,3.0,32,0,WIN,Not Taken

In [63]:
df[df.Team == "IND"]

,Stadium,Team,Toss,Bat,Bowl,Last Matches Performance,Last 3 Matches Performance,Last 6 Matches Performance,Weather,Pitch,Overs,Runs Given,Catches,Win OR Loss,Performance/Wickets
19,LORD'S,IND,LOSS,False,True,NORMAL,BAD,NORMAL,Cool,GREEN,3.2,31,0,WIN,Taken
28,ROSE BOWL STADIUM,IND,LOSS,False,True,GOOD,GOOD,GOOD,Cool,DRY,4.0,39,0,WIN,Taken
31,WANDERS STADIUM,IND,WIN,False,True,BAD,BAD,NORMAL,Cool,DEAD,4.0,44,2,LOSS,Taken
46,LORD'S,IND,LOSS,False,True,GOOD,BAD,NORMAL,Cool,DUSTY,2.2,21,2,LOSS,Taken
49,MELBOURNE,IND,WIN,True,False,GOOD,GOOD,NORMAL,Cool,DRY,4.0,22,1,LOSS,Taken

In [66]:
df[df.Overs >= 3]

,Stadium,Team,Toss,Bat,Bowl,Last Matches Performance,Last 3 Matches Performance,Last 6 Matches Performance,Weather,Pitch,Overs,Runs Given,Catches,Win OR Loss,Performance/Wickets
0,VCA STADIUM,WI,LOSS,True,False,GOOD,GOOD,BAD,Cool,DUSTY,4.0,13,0,LOSS,Taken
1,SUPER SPORT STADIUM,SL,LOSS,True,False,BAD,BAD,BAD,Cool,GREEN,3.0,23,1,WIN,Taken
2,OVAL,ZIM,WIN,True,False,BAD,GOOD,GOOD,Cool,GREEN,3.0,24,0,WIN,Taken
3,BUFFALO PARK,ZIM,WIN,True,False,GOOD,NORMAL,NORMAL,Cool,DUSTY,4.0,23,0,WIN,Taken
4,NEWLANDS CRICKET GROUND,SL,WIN,False,True,NORMAL,BAD,NORMAL,Cool,DUSTY,3.4,21,2,WIN,Taken
5,OVAL,ENG,LOSS,True,False,GOOD,BAD,GOOD,Cool,DEAD,4.0,45,1,LOSS,Not Taken
7,MELBOURNE,AUS,WIN,False,True,BAD,NORMAL,BAD,Cool,GREEN,3.0,24,2,LOSS,Taken
9,OVAL,ENG,LOSS,True,False,NORMAL,GOOD,BAD,Cool,DEAD,4.0,37,0,LOSS,Not Taken
10,NEWLANDS CRICKET GROUND,ENG,LOSS,False,True,GOOD,BAD,NORMAL,Cool,DEAD,3.0,23,3,WIN,Taken
12,VCA STADIUM,SL,WIN,True,False,BAD,NORMAL,NORMAL,Cool,DUSTY,4.0,35,2,LOSS,Taken
13,WANDERS STADIUM,BAN,WIN,True,False,BAD,BAD,GOOD,Cool,GREEN,4.0,44,2,WIN,Not Taken
15,LORD'S,PAK,LOSS,False,True,NORMAL,NORMAL,BAD,Cool,DEAD,4.0,48,0,LOSS,Taken
16,WANDERS STADIUM,WI,LOSS,True,False,BAD,NORMAL,GOOD,Cool,DRY,3.0,20,2,LOSS,Taken
18,EDGBASTON,NZ,LOSS,False,True,BAD,GOOD,BAD,Cool,DEAD,4.0,40,0,WIN,Taken
19,LORD'S,IND,LOSS,False,True,NORMAL,BAD,NORMAL,Cool,GREEN,3.2,31,0,WIN,Taken
21,EDGBASTON,NZ,WIN,False,True,GOOD,GOOD,NORMAL,Cool,DUSTY,4.0,41,1,WIN,Taken
23,EDGBASTON,WI,LOSS,False,True,BAD,GOOD,BAD,Cool,GREEN,4.0,38,0,LOSS,Taken
27,NEWLANDS CRICKET GROUND,NZ,LOSS,False,True,GOOD,NORMAL,GOOD,Cool,GREEN,4.0,51,1,LOSS,Not Taken
28,ROSE BOWL STADIUM,IND,LOSS,False,True,GOOD,GOOD,GOOD,Cool,DRY,4.0,39,0,WIN,Taken
29,LORD'S,BAN,LOSS,True,False,NORMAL,GOOD,GOOD,Cool,DRY,3.0,21,1,LOSS,Taken
31,WANDERS STADIUM,IND,WIN,False,True,BAD,BAD,NORMAL,Cool,DEAD,4.0,44,2,LOSS,Taken
32,OVAL,ENG,WIN,True,False,GOOD,NORMAL,NORMAL,Cool,DEAD,3.0,18,0,WIN,Taken
33,NEWLANDS CRICKET GROUND,BAN,LOSS,True,False,BAD,GOOD,NORMAL,Cool,DEAD,4.0,42,0,WIN,Not Taken
34,WANDERS STADIUM,PAK,LOSS,True,False,GOOD,NORMAL,BAD,Cool,GREEN,3.0,24,2,WIN,Taken
35,LORD'S,AUS,WIN,False,True,BAD,BAD,GOOD,Cool,DUSTY,3.0,30,0,WIN,Not Taken
36,HPCA STADIUM,ENG,WIN,True,False,BAD,BAD,BAD,Cool,DEAD,3.4,20,2,LOSS,Taken
37,NEWLANDS CRICKET GROUND,NZ,LOSS,True,False,GOOD,NORMAL,GOOD,Cool,GREEN,3.0,25,1,LOSS,Taken
39,HPCA STADIUM,NZ,WIN,False,True,NORMAL,NORMAL,BAD,Cool,DRY,3.0,32,2,LOSS,Taken
40,OVAL,NZ,LOSS,False,True,NORMAL,BAD,GOOD,Cool,GREEN,4.0,44,2,WIN,Taken
42,LORD'S,BAN,WIN,True,False,GOOD,BAD,NORMAL,Cool,GREEN,4.0,50,1,LOSS,Not Taken
43,LORD'S,PAK,LOSS,True,False,BAD,NORMAL,NORMAL,Cool,DEAD,3.3,19,0,WIN,Taken
44,NEWLANDS CRICKET GROUND,ENG,LOSS,True,False,NORMAL,GOOD,NORMAL,Cool,GREEN,4.0,43,0,LOSS,Taken
45,NEWLANDS CRICKET GROUND,ENG,LOSS,False,True,GOOD,NORMAL,BAD,Cool,DUSTY,3.0,17,0,LOSS,Taken
47,LORD'S,BAN,WIN,False,True,NORMAL,BAD,BAD,Cool,DRY,3.0,34,0,WIN,Taken
48,LORD'S,BAN,WIN,True,False,BAD,GOOD,GOOD,Cool,DUSTY,3.0,32,0,WIN,Not Taken
49,MELBOURNE,IND,WIN,True,False,GOOD,GOOD,NORMAL,Cool,DRY,4.0,22,1,LOSS,Taken

In [71]:
df.index

RangeIndex(start=0, stop=50, step=1)

In [78]:
df.set_index("Stadium", inplace=True) #set index as any column

KeyError: "None of ['Stadium'] are in the columns"

In [1]:
df.loc["OVAL"] #select rows using index

NameError: name 'df' is not defined

In [2]:
df.reset_index(inplace=True) #set index again to int or numbers
df

NameError: name 'df' is not defined